name: app
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Matthew <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2
  sqlite2: any
  json_rpc_2: any
  web_socket_channel: any
  shelf_web_socket: any
  path: any
  logging: any
  uuid: any
  stack_trace: any
  shelf_static: any
#dev_dependencies:
#  test: ^1.0.0
