name: parkingbrake_server
description: A web server that performs transcoding via Handbrake
# version: 0.1.0-beta
# homepage: https://github.com/sanmadjack/parkingbrake
# author: Matthew <sanmadjack@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: any
  shelf: any
  sqlite2: any
  json_rpc_2: any
  web_socket_channel: any
  shelf_web_socket: any
  path: any
  logging: any
  uuid: any
  stack_trace: any
  shelf_static: any

#dev_dependencies:
#  test: ^1.0.0
